source 'https://github.com/Cocoapods/Specs'
use_frameworks!

target 'MinterCore_Example' do
	pod 'MinterCore', :path => '../'
	pod 'SVProgressHUD'

	target 'MinterCore_Tests' do
		inherit! :search_paths

		pod 'Quick'
		pod 'Nimble'
		pod 'MinterCore', :path => '../'
		pod 'GoldenKeystore', :git => 'https://github.com/sidorov-panda/GoldenKeystore'
	end
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
  end
 end
end
