# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
#- set -o pipefail && xcodebuild clean build test -enableCodeCoverage YES -workspace Example/MinterCore.xcworkspace -scheme MinterCore_Example -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild test -workspace Example/MinterCore.xcworkspace -scheme MinterCore_Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --allow-warnings
